"""
csv_to_mongo.py
────────────────
Reads the CSV generated by serial_to_csv.py and inserts all rows
into MongoDB. Safe to run multiple times — skips rows already inserted
by checking (timestamp, distA, distB) as a unique key.

Usage:
    python csv_to_mongo.py
    python csv_to_mongo.py --csv data/events.csv --uri mongodb://localhost:27017 --db iot_collision
"""

import argparse
import csv
import sys
from datetime import datetime
from pymongo import MongoClient, UpdateOne
from pymongo.errors import BulkWriteError
import os

def _load_env():
    here   = os.path.dirname(os.path.abspath(__file__))
    parent = os.path.dirname(here)
    for env_path in [os.path.join(parent, ".env"), os.path.join(here, ".env")]:
        if not os.path.isfile(env_path):
            continue
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, val = line.partition("=")
                os.environ.setdefault(key.strip(), val.strip())
        break

_load_env()


# ── Type coercions for each column ─────────────────────────────────────────────

def parse_row(row: dict) -> dict:
    """Convert CSV string values to proper Python types."""
    return {
        "wall_time":      row["wall_time"],
        "timestamp_ms":   int(row["timestamp"]),
        "distA":          float(row["distA"]),
        "distB":          float(row["distB"]),
        "vehicleA":       bool(int(row["vehicleA"])),
        "vehicleB":       bool(int(row["vehicleB"])),
        "distanceDiff":   float(row["distanceDiff"]),
        "speedA":         float(row["speedA"]),
        "approachingA":   bool(int(row["approachingA"])),
        "speedB":         float(row["speedB"]),
        "approachingB":   bool(int(row["approachingB"])),
        "avgSpeed":       float(row["avgSpeed"]),
        "accelerationA":  float(row["accelerationA"]),   # new
        "accelerationB":  float(row["accelerationB"]),   # new
        "riskLevel":      int(row["riskLevel"]),
        "inserted_at":    datetime.utcnow(),
    }


# ── Main loader ────────────────────────────────────────────────────────────────

def load(csv_path: str, mongo_uri: str, db_name: str, collection_name: str, batch_size: int):
    # Connect
    client     = MongoClient(mongo_uri, serverSelectionTimeoutMS=5000)
    try:
        client.admin.command("ping")
    except Exception as e:
        print(f"ERROR: Cannot connect to MongoDB at {mongo_uri}\n{e}")
        sys.exit(1)

    db         = client[db_name]
    collection = db[collection_name]

    # Ensure a unique index so re-runs are idempotent
    collection.create_index(
        [("timestamp_ms", 1), ("distA", 1), ("distB", 1)],
        unique=True,
        name="unique_reading"
    )
    collection.create_index("wall_time")
    collection.create_index("riskLevel")

    # Read CSV
    print(f"Reading {csv_path} …")
    try:
        with open(csv_path, newline="") as f:
            reader = csv.DictReader(f)
            all_rows = list(reader)
    except FileNotFoundError:
        print(f"ERROR: File not found: {csv_path}")
        sys.exit(1)

    total      = len(all_rows)
    inserted   = 0
    skipped    = 0
    errors     = 0
    batch      = []

    print(f"Found {total} rows. Inserting into {db_name}.{collection_name} …\n")

    for i, row in enumerate(all_rows, 1):
        try:
            doc = parse_row(row)
        except (KeyError, ValueError) as e:
            print(f"  [row {i}] Parse error: {e} — skipping")
            errors += 1
            continue

        # Use upsert so duplicates are silently ignored
        batch.append(
            UpdateOne(
                {
                    "timestamp_ms": doc["timestamp_ms"],
                    "distA":        doc["distA"],
                    "distB":        doc["distB"],
                },
                {"$setOnInsert": doc},
                upsert=True,
            )
        )

        if len(batch) >= batch_size:
            ins, skip = _flush(collection, batch)
            inserted += ins
            skipped  += skip
            batch     = []
            print(f"  Progress: {i}/{total} rows processed …")

    # Flush remainder
    if batch:
        ins, skip = _flush(collection, batch)
        inserted += ins
        skipped  += skip

    print(f"\n✓ Done.")
    print(f"  Total rows   : {total}")
    print(f"  Inserted     : {inserted}")
    print(f"  Skipped (dup): {skipped}")
    print(f"  Parse errors : {errors}")

    client.close()


def _flush(collection, batch: list) -> tuple[int, int]:
    """Execute a batch of upserts and return (inserted, skipped) counts."""
    try:
        result   = collection.bulk_write(batch, ordered=False)
        inserted = result.upserted_count
        skipped  = len(batch) - inserted
        return inserted, skipped
    except BulkWriteError as bwe:
        # Some were duplicates — that is expected
        inserted = bwe.details.get("nUpserted", 0)
        skipped  = len(batch) - inserted
        return inserted, skipped


# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="CSV → MongoDB Loader")
    parser.add_argument("--csv",        default="data/events.csv",         help="Path to CSV file")
    parser.add_argument("--uri",        default=os.getenv("MONGO_URI", "mongodb://localhost:27017"), help="MongoDB URI")
    parser.add_argument("--db",         default="iot_collision",            help="Database name")
    parser.add_argument("--collection", default="iot_events",               help="Collection name")
    parser.add_argument("--batch",      default=500, type=int,              help="Batch insert size")
    args = parser.parse_args()

    load(
        csv_path=args.csv,
        mongo_uri=args.uri,
        db_name=args.db,
        collection_name=args.collection,
        batch_size=args.batch,
    )


if __name__ == "__main__":
    main()